---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: API documentation for the application
paths:
  "/api/admin_portal/v1/users":
    get:
      summary: List Users
      tags:
      - Users
      parameters:
      - name: continent_id
        in: query
        description: Filter by continent
        schema:
          type: string
      - name: country_id
        in: query
        description: Filter by country
        schema:
          type: string
      - name: state_id
        in: query
        description: Filter by state
        schema:
          type: string
      - name: city_id
        in: query
        description: Filter by city
        schema:
          type: string
      responses:
        '200':
          description: Users found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/user"
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
        continent_id:
          type: integer
          nullable: true
        country_id:
          type: integer
          nullable: true
        state_id:
          type: integer
          nullable: true
        city_id:
          type: integer
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - created_at
      - updated_at
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
