default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['PGUSER'] || 'postgres' %>
  password: <%= ENV['PGPASSWORD'] || 'postgres' %>
  port: <%= ENV['PGPORT'] || 5432 %>
  host: <%= ENV['PGHOST'] || 'localhost' %>

development:
  <<: *default
  database: geo_user_portal
  host: localhost

test:
  <<: *default
  database: geo_user_portal_test
  host: localhost

production:
  <<: *default
  database: <%= ENV['PGDATABASE'] %>
