default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: geo_user_portal

test:
  <<: *default
  database: geo_user_portal_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
