default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: geo_user_portal

test:
  <<: *default
  database: geo_user_portal_test

production:
  <<: *default
  host: <%= ENV['PGHOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  port: <%= ENV['PGPORT'] %>
  database: <%= ENV['PGDATABASE'] %>