default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  port: <%= ENV['PGPORT'] %>
  host: <%= ENV['PGHOST'] %>

development:
  <<: *default
  database: geo_user_portal
  host: localhost

test:
  <<: *default
  database: geo_user_portal_test
  host: localhost

production:
  <<: *default
  database: <%= ENV['PGDATABASE'] %>
